CREATE TABLE "public"."trees" (
	"id" text NOT NULL,
	"lat" text,
	"lng" text,
	"artdtsch" text,
	"artbot" text,
	"gattungdeutsch" text,
	"gattung" text,
	"strname" text,
	"hausnr" text,
	"zusatz" text,
	"pflanzjahr" text,
	"standalter" text,
	"kronedurch" text,
	"stammumfg" text,
	"type" text,
	"baumhoehe" text,
	"bezirk" text,
	"eigentuemer" text,
	"adopted" text,
	"watered" text,
	"radolan_sum" int4,
	"radolan_days" _int4,
	"geom" geometry(point, 4326),
	"standortnr" text,
	"kennzeich" text,
	"caretaker" text,
	"gmlid" text,
	PRIMARY KEY ("id")
);

